### ISSUE TITLE
[DS] Document dynamic sampling questions and considerations

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/develop#618]
https://github.com/getsentry/develop/pull/613 provides a initial foundation for the DS/baggage docs - but there were some outstanding TODOs still left to document. This GH issue provides a place for us to store that:

#### TODO:

- [ ] Consequences of immutable baggage and impacts it might have on DS UX
- [ ] Document challenge about 3rd party APIs that are instrumented with DS compatible SDKs
- [ ] Add note about sample rate smoothing (and how it uses `sample_rate` in trace contexts)
- [ ] Dynamic Sampling on traces vs. transactions

**Comment by Lms24** [comment]
* [ ] How to handle the edge case of receiving a `baggage` header with `sentry-` keyed entries but no `sentry-trace` header
